### ISSUE TITLE
TimeOut Exception not being throw

### ISSUE THREAD

**Issue by Marco-GG** [loentar/staff#232]
Hello loentar,

Using staff as a SOAP client I found that when a connection timeout occurs,  the failed operations throws an AssertException instead of the expected TimeoutException.  Debugging this bug, I found the source of the problem in the next line of the ServiceClient Invoker:

    if (m_pEnv->error->status_code == AXIS2_ERROR_RESPONSE_TIMED_OUT)
    {
      STAFF_THROW(TimeoutException, "Axis2/C client send receive failed (Timeout). error: " + GetLastErrorStr())
    }

The bug is the condition of the if statement due that it checks the error code for a time-out with the status code, while it should have been validated using the error_code. I mean:

    if (m_pEnv->error->error_code == AXIS2_ERROR_RESPONSE_TIMED_OUT)
    {
      STAFF_THROW(TimeoutException, "Axis2/C client send receive failed (Timeout). error: " + GetLastErrorStr())
    }

Making this change and rebuilding the staff lib I could check that the TimeoutException is thrown when this error is detected. Please, whenever you can run your own tests in order to verify and apply this fix.

Regards,
Marco

P.S: My apologies for not creating a branch, but I think that this little bug don't  deserves one...

**Comment by loentar** [comment]
I cannot check it now, but hope it works. Thanks for the tip :)
